include:
  - board: xiao_ble
    zmk_board_variant: zmk
    shield: totem_left
  - board: xiao_ble
    zmk_board_variant: zmk
    shield: totem_right
  - board: xiao_ble
    zmk_board_variant: zmk
    shield: settings_reset
